name: Test PR

on:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: Test Pull Request
    runs-on: ubuntu-latest
    if: github.repository == 'gutsche-lab/blik'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install qt libraries
      run: |
        sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 \
          libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 \
          libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 xvfb
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-cov pytest-qt codecov PyQt5
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        xvfb-run pytest --cov=./blik
        codecov
    - name: Upload report to codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
